# Generated by the Contextually Blueprint Compiler
from __future__ import annotations
from typing import Any, Dict, List, Optional
from datetime import date, datetime
from uuid import UUID
from pydantic import BaseModel, Field


class ApiResponse(BaseModel):
    code: Optional[int] = None
    type: Optional[str] = None
    message: Optional[str] = None


class Category(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class Pet(BaseModel):
    id: Optional[int] = None
    category: Optional["Category"] = None
    name: str
    photoUrls: List[str]
    tags: Optional[List["Tag"]] = None
    status: Optional[str] = None


class Tag(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class Order(BaseModel):
    id: Optional[int] = None
    petId: Optional[int] = None
    quantity: Optional[int] = None
    shipDate: Optional[datetime] = None
    status: Optional[str] = None
    complete: Optional[bool] = None


class User(BaseModel):
    id: Optional[int] = None
    username: Optional[str] = None
    firstName: Optional[str] = None
    lastName: Optional[str] = None
    email: Optional[str] = None
    password: Optional[str] = None
    phone: Optional[str] = None
    userStatus: Optional[int] = None


class UploadfileParameters(BaseModel):
    petId: int


class FindpetsbystatusParameters(BaseModel):
    status: List


class FindpetsbytagsParameters(BaseModel):
    tags: List


class GetpetbyidParameters(BaseModel):
    petId: int


class UpdatepetwithformParameters(BaseModel):
    petId: int


class DeletepetParameters(BaseModel):
    api_key: Optional[str] = None
    petId: int


class GetorderbyidParameters(BaseModel):
    orderId: int


class DeleteorderParameters(BaseModel):
    orderId: int


class GetuserbynameParameters(BaseModel):
    username: str


class UpdateuserParameters(BaseModel):
    username: str


class DeleteuserParameters(BaseModel):
    username: str


class LoginuserParameters(BaseModel):
    username: str
    password: str

