name: Build and Release CX Shell

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e .[all]

      - name: Run Pytest
        run: uv run pytest

  build:
    name: Build Executable on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # By building on an older, stable LTS version of Ubuntu, we ensure
        # the compiled binary is linked against an older version of glibc,
        # making it compatible with a much wider range of Linux systems.
        os: [ubuntu-22.04, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies and build tools
        run: uv pip install -e .[all]

      - name: Build the executable with PyInstaller
        run: uv run pyinstaller cx.spec

      - name: Prepare artifact name and path
        id: prepare_artifact
        shell: bash
        run: |
          VERSION=${{ github.ref_name }}
          OS_NAME=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')

          if [ "${{ runner.os }}" == "Windows" ]; then
            EXECUTABLE_PATH="dist/cx.exe"
            ARCHIVE_NAME="cx-${VERSION}-${OS_NAME}-amd64.zip"
            7z a $ARCHIVE_NAME $EXECUTABLE_PATH
            echo "ASSET_PATH=${ARCHIVE_NAME}" >> $GITHUB_ENV
            echo "ASSET_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV
          else
            EXECUTABLE_PATH="dist/cx"
            ARCHIVE_NAME="cx-${VERSION}-${OS_NAME}-x86_64.tar.gz"
            tar -czvf $ARCHIVE_NAME -C dist cx
            echo "ASSET_PATH=${ARCHIVE_NAME}" >> $GITHUB_ENV
            echo "ASSET_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV
          fi

      - name: Upload artifact for release job
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ASSET_NAME }}
          path: ${{ env.ASSET_PATH }}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: release-assets/**/*
